export type CineQuestColorTokens = {
  primary: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  secondary: string;
  onSecondary: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  tertiary: string;
  onTertiary: string;
  tertiaryContainer: string;
  onTertiaryContainer: string;
  error: string;
  onError: string;
  errorContainer: string;
  onErrorContainer: string;
  background: string;
  onBackground: string;
  surface: string;
  surfaceContainerLowest: string;
  surfaceContainerLow: string;
  surfaceContainer: string;
  surfaceContainerHigh: string;
  surfaceContainerHighest: string;
  onSurface: string;
  onSurfaceVariant: string;
  inverseSurface: string;
  inverseOnSurface: string;
  outline: string;
  outlineVariant: string;
  successGreen: string;
  infoBlue: string;
  warningYellow: string;
  borderGray: string;
};

export const lightColors: CineQuestColorTokens = {
  primary: '#2b6c00',
  onPrimary: '#ffffff',
  primaryContainer: '#58cc02',
  onPrimaryContainer: '#1e5000',
  secondary: '#006590',
  onSecondary: '#ffffff',
  secondaryContainer: '#2fb8ff',
  onSecondaryContainer: '#004666',
  tertiary: '#755b00',
  onTertiary: '#ffffff',
  tertiaryContainer: '#ddad00',
  onTertiaryContainer: '#574300',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  background: '#f9f9f9',
  onBackground: '#1a1c1c',
  surface: '#f9f9f9',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f4f3f3',
  surfaceContainer: '#eeeeed',
  surfaceContainerHigh: '#e8e8e8',
  surfaceContainerHighest: '#e2e2e2',
  onSurface: '#1a1c1c',
  onSurfaceVariant: '#3f4a36',
  inverseSurface: '#2f3131',
  inverseOnSurface: '#f1f1f0',
  outline: '#6f7b64',
  outlineVariant: '#becbb1',
  successGreen: '#58cc02',
  infoBlue: '#1cb0f6',
  warningYellow: '#ffc800',
  borderGray: '#eeeeee',
};

// Dark palette — M3 dark scheme; activate by calling getTheme('dark')
export const darkColors: CineQuestColorTokens = {
  primary: '#6be026',
  onPrimary: '#082100',
  primaryContainer: '#1f5100',
  onPrimaryContainer: '#87fe45',
  secondary: '#88ceff',
  onSecondary: '#001e2e',
  secondaryContainer: '#004c6e',
  onSecondaryContainer: '#c8e6ff',
  tertiary: '#f4bf00',
  onTertiary: '#3d2f00',
  tertiaryContainer: '#594400',
  onTertiaryContainer: '#ffdf92',
  error: '#ffb4ab',
  onError: '#690005',
  errorContainer: '#93000a',
  onErrorContainer: '#ffdad6',
  background: '#111411',
  onBackground: '#e2e4df',
  surface: '#111411',
  surfaceContainerLowest: '#0b0f0a',
  surfaceContainerLow: '#191d18',
  surfaceContainer: '#1d211c',
  surfaceContainerHigh: '#272b26',
  surfaceContainerHighest: '#323631',
  onSurface: '#e2e4df',
  onSurfaceVariant: '#c2ceb5',
  inverseSurface: '#e2e4df',
  inverseOnSurface: '#2f3131',
  outline: '#8c9882',
  outlineVariant: '#3f4a36',
  successGreen: '#6be026',
  infoBlue: '#1cb0f6',
  warningYellow: '#ffc800',
  borderGray: '#272b26',
};
